"""Coco 中文文案重打：同步官方底座之后跑一条命令，把中文改回来

为什么需要它：同步官方是「快照式替换」——我们改过的官方文件会被换回英文原文。
本脚本把这些**纯文案**改动登记成一张表（文件 + 官方原文 + 我们的中文），
同步之后执行：

    python3 scripts/coco_cn_strings.py --apply     # 自动改回中文
    python3 scripts/coco_cn_strings.py             # 只检查（默认），不写文件
    python3 scripts/coco_cn_strings.py --list      # 列出全部条目

三种结果，**绝不静默**：
  OK      —— 已经是中文（跳过）
  APPLY   —— 官方原文还在，已替换（--apply）/ 待替换（--check）
  ANCHOR  —— 官方原文和中文都找不到：官方改过这段文案，需按 patches/README.md
             （第 23 / 24 处）在新版里重新实现，再更新本表

退出码：0 = 全部到位；1 = 有待替换或锚点失效。
配套：check_coco_hooks.py 第 58–68 项、patches/README.md 第 23 / 24 处。
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

# (相对路径, 官方原文, 中文文案) —— 由改动提交的 diff 生成，改文案时同步更新这里
ENTRIES = [
    ('gateway/platforms/base.py', '            hint = "Reply with the number, the option text, or your own answer."',
     '            # COCO-PATCH 2026-09-30：选项提示行改中文（官方是英文，经纪人每次选选项都看得见）\n            hint = "回数字、选项原文，或直接说你的答案。"'),
    ('gateway/platforms/base.py', '                hint = ("Multiple selections allowed — reply with the numbers separated by commas "\n                        "or spaces (e.g. \\"1, 3\\"), the option text, or your own answer.")',
     '                hint = "可以多选：回数字（用逗号或空格隔开，如「1, 3」）、选项原文，或直接说你的答案。"'),
    ('gateway/relay/adapter.py', '            options.append({"id": "other", "label": "✏️ Other (type your answer)"})',
     '            options.append({"id": "other", "label": "✏️ 其他（我来补充）"})'),
    ('gateway/run_notifications.py', '                f"☤ **Update needs your input:**\\n\\n{prompt_text}{default_hint}\\n\\n"\n                f"Reply `{_p}approve` (yes) or `{_p}deny` (no), or type your answer directly."',
     '                f"☤ **更新需要你确认：**\\n\\n{prompt_text}{default_hint}\\n\\n"\n                f"回 `{_p}approve` 表示同意、`{_p}deny` 表示不同意，也可以直接说你的答案。"'),
    ('hermes_cli/auth_codex.py', '                "Import these credentials? (a separate login is recommended) [y/N]: ", default="n"):',
     '                "要导入这些凭据吗？（更建议单独登录一次）[y/N]: ", default="n"):'),
    ('hermes_cli/cli_commands_mixin.py', '                "  Restart recommended for gateway/dashboard processes to pick up state.db changes.")',
     '                "  建议重启网关/看板进程，让它们读新的 state.db。")'),
    ('hermes_cli/cli_tui_mixin.py', '                        other_label = f"  ❯ {mid}. " + (other_suffix or "Other (type below)")',
     '                        other_label = f"  ❯ {mid}. " + (other_suffix or "其他（在下面输入）")'),
    ('hermes_cli/cli_tui_mixin.py', '                        other_label = f"  ❯ {mid}. " + (other_suffix or "Other (type your answer)")',
     '                        other_label = f"  ❯ {mid}. " + (other_suffix or "其他（我来补充）")'),
    ('hermes_cli/cli_tui_mixin.py', '                        other_label = f"    {mid}. " + (other_suffix or "Other (type your answer)")',
     '                        other_label = f"    {mid}. " + (other_suffix or "其他（我来补充）")'),
    ('hermes_cli/cli_tui_mixin.py', '        other_label = _label(other_idx, "Other (type below)" if freetext else "Other (type your answer)")',
     '        other_label = _label(other_idx, "其他（在下面输入）" if freetext else "其他（我来补充）")'),
    ('hermes_cli/doctor_platform.py', '    elif check_bool(v >= (3, 10), label, (label, "(3.10+ recommended)")) and v < (3, 11):\n        check_warn("Python 3.11+ recommended for RL Training tools (tinker requires >= 3.11)")',
     '    elif check_bool(v >= (3, 10), label, (label, "(建议 3.10+)")) and v < (3, 11):\n        check_warn("RL 训练类工具建议 Python 3.11+（tinker 要求 >= 3.11）")'),
    ('hermes_cli/gateway.py', '        print_info("  This is fine for LXC/container environments but not recommended on bare-metal hosts.")',
     '        print_info("  这在 LXC/容器环境里没问题，但裸机主机上不建议这样做。")'),
    ('hermes_cli/gateway.py', '    print_info("    2. Switch to a per-user service (recommended for personal use):")',
     '    print_info("    2. 换成为当前用户运行的服务（个人自用推荐这个）：")'),
    ('hermes_cli/gateway.py', '        "  Pass --force to start a foreground gateway anyway (not recommended\\n"\n        "  while the service is running)."',
     '        "  确实要前台起一个网关，就加 --force（不建议：服务还在跑的时候这样会冲突）。"'),
    ('hermes_cli/gateway.py', '        "  This is the recommended setup for the s6 container image — the\\n"',
     '        "  这是 s6 容器镜像下推荐的方式 —— 网关崩了也会自动重启。\\n"'),
    ('hermes_cli/gateway.py', '        "WSL note:", "  The gateway is running in foreground/manual mode (recommended for WSL).",',
     '        "WSL 说明：", "  网关正以前台/手动方式运行（WSL 下推荐这样）。",'),
    ('hermes_cli/gateway_migrate.py', '        "⚠ Your profiles each run their own gateway. A single multiplexed gateway is the recommended",',
     '        "⚠ 每个 profile 各自跑一个网关。更推荐用单个多路复用网关：",'),
    ('hermes_cli/gateway_setup_wizard.py', '        "Use DM pairing approval (recommended)", "Allow all direct messages", "Only allow listed user IDs",',
     '        "用私聊配对审批（推荐）", "允许所有私聊", "只允许名单里的用户 ID",'),
    ('hermes_cli/gateway_setup_wizard.py', '        "Disable group chats (recommended)", "Allow all group chats", "Only allow listed group chat IDs",',
     '        "关闭群聊（推荐）", "允许所有群聊", "只允许名单里的群 ID",'),
    ('hermes_cli/gateway_setup_wizard.py', '    method_choices = ["Scan QR code to add bot automatically (recommended)", "Enter existing App ID and App Secret manually"]',
     '    method_choices = ["扫码自动添加机器人（推荐）", "手动填写已有的 App ID 与 App Secret"]'),
    ('hermes_cli/gateway_setup_wizard.py', '    access_choices = ["Use DM pairing approval (recommended)", "Allow all direct messages", "Only allow listed user OpenIDs"]',
     '    access_choices = ["用私聊配对审批（推荐）", "允许所有私聊", "只允许名单里的用户 OpenID"]'),
    ('hermes_cli/main_platform_setup.py', '         "  1. Separate bot number (recommended)",',
     '         "  1. Separate bot number（推荐）",'),
    ('hermes_cli/model_setup_flows_azure.py', '         "     Recommended by Microsoft. Works for both OpenAI-style and Anthropic-style endpoints.",',
     '         "     微软推荐的方式，兼容 OpenAI 风格与 Anthropic 风格的端点。",'),
    ('hermes_cli/model_setup_flows_bedrock.py', '    _say("  Choose authentication method:", "", "    1. IAM credential chain (recommended)",',
     '    _say("  Choose authentication method:", "", "    1. IAM 凭据链（推荐）",'),
    ('hermes_cli/onepassword_secrets_cli.py', '            flag("--no-verify", "Store without probing 1Password first (not recommended)"),',
     '            flag("--no-verify", "不先探测 1Password 直接存（不建议）"),'),
    ('hermes_cli/secrets_cli.py', '            flag("--no-verify", "Store without probing Bitwarden first (not recommended)"),',
     '            flag("--no-verify", "不先探测 Bitwarden 直接存（不建议）"),'),
    ('hermes_cli/setup_platforms.py', '          "  [1] Automatic (recommended)",',
     '          "  [1] 自动（推荐）",'),
    ('hermes_cli/setup_quick.py', '        "Set up messaging now (recommended)", "Skip — set up later with \'hermes setup gateway\'",',
     '        "现在就接消息通道（推荐）", "先跳过 —— 之后用 \'coco setup gateway\' 再接",'),
    ('hermes_cli/subcommands/gateway.py', '    "(not recommended: two pollers on one bot token, port conflicts)")',
     '    "（不建议：同一个机器人令牌会有两个轮询者，端口也容易冲突）")'),
    ('hermes_cli/subcommands/gateway.py', '        "run", help="Run gateway in foreground (recommended for WSL, Docker, Termux)")',
     '        "run", help="前台运行网关（WSL / Docker / Termux 下推荐）")'),
    ('hermes_cli/subcommands/sessions.py', '        help="Skip the timestamped state.db backup taken before writing (not recommended)")',
     '        help="跳过写入前的带时间戳 state.db 备份（不建议）")'),
    ('hermes_cli/subcommands/sessions.py', '    _flag(sessions_repair, "--no-backup", help="Skip the timestamped backup copy (not recommended)")',
     '    _flag(sessions_repair, "--no-backup", help="跳过带时间戳的备份副本（不建议）")'),
    ('hermes_cli/tools_config_providers.py', '    choices = ["Enable public URLs without automatic expiry (recommended)", "Disable stored public URLs",',
     '    choices = ["开启公开链接、不自动过期（推荐）", "关闭保存的公开链接",'),
    ('hermes_cli/tools_config_providers.py', '        "Auto — use your main model / aggregator fallback (recommended)",',
     '        "自动 —— 用你的主模型 / 聚合服务兜底（推荐）",'),
    ('hermes_cli/uninstall.py', '    print("     (Recommended - you can reinstall later with your settings intact)")',
     '    print("     (推荐：只删程序，配置和会话都留着，之后重装还在)")'),
    ('hermes_cli/uninstall.py', '    print("     (Warning: This deletes all configs, sessions, and logs permanently)")',
     '    print("     (注意：配置、会话、日志会一起永久删除)")'),
    ('tools/clarify_tool.py', '        "as recommended, and auto-appends an "\n        "\'Other\' free-text row), multi-select (multi_select=true), or "',
     '        "as recommended. Some surfaces append an \'Other\' free-text row and "\n        "some do not — when in doubt add your own \'其他（我来补充）\' as the last "\n        "choice), multi-select (multi_select=true), or "'),
    ('hermes_cli/doctor.py', "    ('Security Advisories', _check_security_advisories), ('MCP Server Security', _check_mcp_security),\n    ('Python Environment', _check_python_environment), ('SSL / CA Certificates', _check_certificates),\n    ('Required Packages', _check_required_packages), ('Configuration Files', _check_env_file),",
     "    ('安全公告', _check_security_advisories), ('MCP 服务安全', _check_mcp_security),\n    ('Python 环境', _check_python_environment), ('SSL 证书', _check_certificates),\n    ('依赖包', _check_required_packages), ('配置文件', _check_env_file),"),
    ('hermes_cli/doctor.py', "    ('xAI Model Retirement (May 15, 2026)', _check_xai_retirement),\n    ('Plugin import paths (removed Sep 14, 2026)', _check_plugin_compat), ('Auth Providers', _check_auth_providers),\n    ('Directory Structure', _check_directory_structure), (None, _check_state_db), (None, _check_checkpoint_store),",
     "    ('xAI 模型下线（2026-05-15）', _check_xai_retirement),\n    ('插件导入路径（2026-09-14 移除）', _check_plugin_compat), ('模型服务商登录', _check_auth_providers),\n    ('目录结构', _check_directory_structure), (None, _check_state_db), (None, _check_checkpoint_store),"),
    ('hermes_cli/doctor.py', "    ('External Tools', _check_git_and_rg), (None, _check_terminal_backend), (None, _check_node_and_browser),\n    (None, _check_npm_audit), ('API Connectivity', _check_api_connectivity),\n    ('Tool Availability', _check_tool_availability), ('Skills Hub', _check_skills_hub),\n    ('Memory Provider', _check_memory_provider), (None, _check_profiles),",
     "    ('外部工具', _check_git_and_rg), (None, _check_terminal_backend), (None, _check_node_and_browser),\n    (None, _check_npm_audit), ('模型服务连通性', _check_api_connectivity),\n    ('可用工具', _check_tool_availability), ('技能源', _check_skills_hub),\n    ('记忆存储', _check_memory_provider), (None, _check_profiles),"),
    ('hermes_cli/doctor.py', '        print(color(f"Unknown advisory ID: {ack_target!r}. Known IDs: {\', \'.join(sorted(valid_ids)) or \'(none)\'}", Colors.RED))',
     '        print(color(f"认不出这条公告编号：{ack_target!r}。可用编号：{\', \'.join(sorted(valid_ids)) or \'（无）\'}", Colors.RED))'),
    ('hermes_cli/doctor.py', '        print(color(f"  ✓ Acknowledged advisory {ack_target}. It will no longer trigger startup banners.", Colors.GREEN))',
     '        print(color(f"  ✓ 已确认公告 {ack_target}，启动时不再提示。", Colors.GREEN))'),
    ('hermes_cli/doctor.py', '        print(color(f"  ✗ Could not save the acknowledgement for {ack_target}. Make sure {_DHH}/config.yaml is "\n                    f"writable (`hermes config path` prints the exact file), then re-run "\n                    f"`hermes doctor --ack {ack_target}`.", Colors.RED))',
     '        print(color(f"  ✗ 没能保存 {ack_target} 的确认记录。请确认 {_DHH}/config.yaml 可写"\n                    f"（「coco config path」能打印它的确切路径），然后重跑 "\n                    f"「coco doctor --ack {ack_target}」。", Colors.RED))'),
    ('hermes_cli/doctor.py', '        print(color(f"  Fixed {total.fixed} issue(s).", Colors.GREEN, Colors.BOLD), end="")\n        print(color(f" {len(remaining)} issue(s) require manual intervention.", Colors.YELLOW, Colors.BOLD) if remaining else "")',
     '        print(color(f"  已自动修好 {total.fixed} 个问题。", Colors.GREEN, Colors.BOLD), end="")\n        print(color(f" 另有 {len(remaining)} 个问题需要你手动处理。", Colors.YELLOW, Colors.BOLD) if remaining else "")'),
    ('hermes_cli/doctor.py', '        print(color(f"  Found {len(remaining)} issue(s) to address:", Colors.YELLOW, Colors.BOLD))',
     '        print(color(f"  发现 {len(remaining)} 个需要处理的问题：", Colors.YELLOW, Colors.BOLD))'),
    ('hermes_cli/doctor.py', '            print(color("  Tip: run \'hermes doctor --fix\' to auto-fix what\'s possible.", Colors.DIM))',
     '            print(color("  提示：能自动修的问题，跑「coco doctor --fix」会帮你修。", Colors.DIM))'),
    ('hermes_cli/doctor.py', '        print(color("  All checks passed! 🎉", Colors.GREEN, Colors.BOLD))',
     '        print(color("  全部检查通过！🎉", Colors.GREEN, Colors.BOLD))'),
    ('hermes_cli/doctor.py', '                 "│                 🩺 Hermes Doctor                        │",',
     '                 "│                 🩺 Coco 部署体检                        │",'),
    ('hermes_cli/doctor_platform.py', '        "docker": f"run `{cmd}`, then recreate all Hermes containers", "apt": f"run `{cmd}`"}.get(method, "run `hermes update`")',
     '        "docker": f"跑 `{cmd}`，然后重建全部容器", "apt": f"跑 `{cmd}`"}.get(method, "跑 `coco update`")'),
    ('hermes_cli/doctor_platform.py', '                    "Re-sync version files (e.g. run \'hermes update\', or set hermes_cli/__init__.py __version__ to match pyproject.toml)", issues)',
     '                    "版本文件不一致：重新同步（跑 \'coco update\'，或把 hermes_cli/__init__.py 的 __version__ 改成与 pyproject.toml 一致）", issues)'),
    ('hermes_cli/doctor_platform.py', '            return check_info("No gateway registered yet — run `hermes gateway install`")',
     '            return check_info("还没有注册网关服务 —— 跑 `coco gateway install`")'),
    ('hermes_cli/doctor_platform.py', '        issues.append(f"Repair the CA bundle: run `hermes doctor --fix`, or `{pip_cmd}`")',
     '        issues.append(f"修复 CA 证书包：跑 `coco doctor --fix`，或 `{pip_cmd}`")'),
    ('hermes_cli/doctor_platform.py', '    "all permission grants. Run `hermes update` to get the stable identifier-pinned signing identity, "',
     '    "all permission grants. Run `coco update` to get the stable identifier-pinned signing identity, "'),
    ('hermes_cli/doctor_platform.py', '                        f"and rotate credentials, then run `hermes doctor --ack {hit.advisory.id}`.", f.manual_issues)',
     '                        f"and rotate credentials, then run `coco doctor --ack {hit.advisory.id}`.", f.manual_issues)'),
    ('hermes_cli/doctor_platform.py', '    link = link_dir / "hermes"',
     '    # Coco 只对外暴露 coco 命令（安装与更新会移除 hermes 软链），所以这里查的是 coco 链接。\n    # 照官方查 hermes 会让每次体检都报一个假问题，`--fix` 还会把 hermes 命令装回来。\n    _coco_only = (PROJECT_ROOT / "scripts" / "coco.sh").exists()\n    link_name = "coco" if _coco_only else "hermes"\n    link = link_dir / link_name'),
    ('tests/hermes_cli/test_doctor.py', '        assert "run `pkg upgrade hermes-agent`" in hint',
     '        assert "跑 `pkg upgrade hermes-agent`" in hint'),
    ('tests/hermes_cli/test_doctor.py', '        assert "Memory Provider" in out',
     '        assert "记忆存储" in out'),
    ('tests/hermes_cli/test_doctor.py', '        assert "Auth Providers" in out',
     '        assert "模型服务商登录" in out'),
    ('tests/hermes_cli/test_doctor_exit_status.py', '    assert ("fixture unresolved problem" if unresolved else "All checks passed") in result.stdout',
     '    assert ("fixture unresolved problem" if unresolved else "全部检查通过") in result.stdout'),
    ('hermes_cli/doctor_platform.py', '        check_warn(f"{name}: cannot prove the database is quiet", "(holder scan is unavailable on Windows)")',
     '        check_warn(f"{name}：没法确认数据库此刻是安静的", "（Windows 上看不了占用进程）")'),
    ('hermes_cli/doctor_platform.py', '        check_info(f"{name} is held by {describe_holder_pid(pid)}: {\', \'.join(sorted(by_pid[pid]))}")',
     '        check_info(f"{name} 正被占用：{describe_holder_pid(pid)} —— {\', \'.join(sorted(by_pid[pid]))}")'),
    ('hermes_cli/doctor_platform.py', '        check_warn(f"{name}: cannot prove the database is quiet",',
     '        check_warn(f"{name}：没法确认数据库此刻是安静的",'),
    ('hermes_cli/doctor_platform.py', '        check_info(f"{name}: no other process holds it right now — the offline conversion can run")',
     '        check_info(f"{name}：当前没有别的进程占用，离线转换可以跑")'),
    ('hermes_cli/doctor_platform.py', '        check_warn(f"Could not list Hermes databases: {exc}")',
     '        check_warn(f"列不出数据库：{exc}")'),
    ('hermes_cli/doctor_platform.py', '            check_warn(f"{name} is in WAL mode ({size}) despite database.journal_mode=delete",',
     '            check_warn(f"{name} 仍是 WAL 模式（{size}），但配置写的是 database.journal_mode=delete",'),
    ('hermes_cli/doctor_platform.py', '                check_warn(f"{name}: journal mode could not be read", f"({error}; cannot rule out WAL exposure)")',
     '                check_warn(f"{name}：读不到日志模式", f"（{error}；没法排除 WAL 风险）")'),
    ('hermes_cli/doctor_platform.py', '                check_info(f"{name}: journal mode could not be read ({error})")',
     '                check_info(f"{name}：读不到日志模式（{error}）")'),
    ('hermes_cli/doctor_platform.py', '            check_warn(f"{name} is in WAL mode on a cross-VM filesystem (virtiofs/9p, {size})",',
     '            check_warn(f"{name} 在跨虚拟机文件系统（virtiofs/9p）上是 WAL 模式（{size}）",'),
    ('hermes_cli/doctor_platform.py', '            check_warn(f"{name} is in WAL mode ({size})", "(exposed to the WAL-reset bug until SQLite is upgraded)")',
     '            check_warn(f"{name} 是 WAL 模式（{size}）", "（SQLite 升级前有 WAL 重置风险）")'),
    ('hermes_cli/doctor_platform.py', '            check_info(f"{name}: WAL journal mode ({size})")',
     '            check_info(f"{name}：WAL 日志模式（{size}）")'),
    ('hermes_cli/doctor_platform.py', '            check_info(f"{name}: rollback journal mode ({size}{\', not exposed\' if vulnerable else \'\'})")',
     '            check_info(f"{name}：回滚日志模式（{size}{\'，无风险\' if vulnerable else \'\'}）")'),
    ('hermes_cli/doctor_platform.py', '        check_info(f"To clear the exposure: {_wal_reset_repair_hint()}")',
     '        check_info(f"消除风险的办法：{_wal_reset_repair_hint()}")'),
    ('hermes_cli/doctor_platform.py', '        return check_ok("Version files consistent", f"({init_version})")',
     '        return check_ok("版本文件一致", f"({init_version})")'),
    ('hermes_cli/doctor_platform.py', '        (check_ok if up else check_info)(f"{static}: up" if up else f"{static}: down (expected if not enabled via env)")',
     '        (check_ok if up else check_info)(f"{static}: up" if up else f"{static}：未运行（没通过环境变量启用时属正常）")'),
    ('hermes_cli/doctor_platform.py', '        issues.append("No host gateway owns the gateway role — start the ONE host multiplexer: "',
     '        issues.append("没有网关在承担网关角色 —— 启动那个唯一的主网关："'),
    ('hermes_cli/doctor_platform.py', '        return check_warn(f"No host gateway owns the gateway role ({len(up)}/{len(slots)} supervision "',
     '        return check_warn(f"没有网关承担网关角色（{len(up)}/{len(slots)} 个监管槽位在位）："'),
    ('hermes_cli/doctor_platform.py', '    check_ok(f"Host gateway: {topology.describe()}")',
     '    check_ok(f"主网关：{topology.describe()}")'),
    ('hermes_cli/doctor_platform.py', '        check_warn(f"LEGACY per-profile gateway slots still supervised: {\', \'.join(legacy_up)}",',
     '        check_warn(f"仍在监管的旧版按配置网关：{\', \'.join(legacy_up)}",'),
    ('hermes_cli/doctor_platform.py', '        issues.append("Fold the legacy per-profile gateways into the host gateway: "',
     '        issues.append("把旧版按配置的网关并进主网关："'),
    ('hermes_cli/doctor_platform.py', '        return check_warn("SSL certificate check skipped", str(e))',
     '        return check_warn("跳过 SSL 证书检查", str(e))'),
    ('hermes_cli/doctor_platform.py', '        return check_ok("SSL CA certificate bundle is valid")',
     '        return check_ok("SSL 根证书包正常")'),
    ('hermes_cli/doctor_platform.py', '        return check_warn("SSL certificate check skipped", str(e))\n    check_fail("SSL CA certificate bundle is broken", first_error)',
     '        return check_warn("跳过 SSL 证书检查", str(e))\n    check_fail("SSL 根证书包有问题", first_error)'),
    ('hermes_cli/doctor_platform.py', '        check_ok("SSL CA certificate bundle repaired (certifi reinstalled)")',
     '        check_ok("SSL 根证书包已修好（重装了 certifi）")'),
    ('hermes_cli/doctor_platform.py', '        return check_warn("Gateway service linger", f"(could not import gateway helpers: {e})")',
     '        return check_warn("网关服务常驻（linger）", f"（导入网关辅助函数失败：{e}）")'),
    ('hermes_cli/doctor_platform.py', '        return check_warn("Could not verify systemd linger", f"({linger_detail})")',
     '        return check_warn("没能确认 systemd linger 状态", f"({linger_detail})")'),
    ('hermes_cli/doctor_platform.py', '        check_info("Run: sudo loginctl enable-linger $USER")\n        issues.append("Enable linger for the gateway user service: sudo loginctl enable-linger $USER")',
     '        check_info("执行：sudo loginctl enable-linger $USER")\n        issues.append("让网关用户服务常驻：sudo loginctl enable-linger $USER")'),
    ('hermes_cli/doctor_platform.py', '        return check_warn("macOS TCC grant check", "(could not read code-signing requirement of the desktop bundle)")',
     '        return check_warn("macOS 权限授予检查", "（读不到桌面版的签名要求）")'),
    ('hermes_cli/doctor_platform.py', '        return check_warn("macOS TCC grants will reset after every update", _TCC_CDHASH_DETAIL)',
     '        return check_warn("macOS 的权限授予会在每次更新后重置", _TCC_CDHASH_DETAIL)'),
    ('hermes_cli/doctor_platform.py', '    check_ok("macOS TCC signing identity is stable", _TCC_STABLE_DETAIL["certificate" in dr.lower()])\n    check_info("If macOS still re-prompts for permissions (toggle shows ON): the stored grant is stale — run "',
     '    check_ok("macOS 的签名身份稳定", _TCC_STABLE_DETAIL["certificate" in dr.lower()])\n    check_info("如果 macOS 还是反复要权限（开关显示已开）：存的授权过期了 —— 执行 "'),
    ('hermes_cli/doctor_platform.py', '            return check_ok("macOS TCC anchor active", f"({detail})")',
     '            return check_ok("macOS 授权锚点生效", f"({detail})")'),
    ('hermes_cli/doctor_platform.py', '            return check_ok("macOS TCC anchor installed", f"({anchored})")\n        check_warn("macOS TCC anchor missing" if status == "missing" else "macOS TCC anchor stale", f"({detail})")',
     '            return check_ok("macOS 授权锚点已装好", f"({anchored})")\n        check_warn("macOS 授权锚点缺失" if status == "missing" else "macOS 授权锚点是旧的", f"({detail})")'),
    ('hermes_cli/doctor_platform.py', '        check_info("One switch silences all macOS folder prompts: grant your terminal app Full Disk Access and Hermes "',
     '        check_info("一个开关能关掉 macOS 的所有目录弹窗：给终端 App 开「完全磁盘访问权限」，Coco "'),
    ('hermes_cli/doctor_platform.py', '        check_ok("macOS Full Disk Access granted", "(no per-folder permission prompts will occur)")',
     '        check_ok("macOS 完全磁盘访问权限已授予", "（不会再逐个目录弹权限）")'),
    ('hermes_cli/doctor_platform.py', '        return check_ok("No active security advisories")',
     '        return check_ok("没有需要处理的安全公告")'),
    ('hermes_cli/doctor_platform.py', '            check_warn(f"{h.package}=={h.installed_version} still installed (advisory {h.advisory.id} acknowledged)")',
     '            check_warn(f"仍处于安装状态（公告 {h.advisory.id} 已确认）")'),
    ('hermes_cli/doctor_platform.py', '            check_info(f"SQLite source id: {(src[:48] + \'…\') if len(src) > 48 else src}")',
     '            check_info(f"SQLite 源码版本号：{(src[:48] + \'…\') if len(src) > 48 else src}")'),
    ('hermes_cli/doctor_platform.py', '                check_warn(name, "(optional, not installed)")',
     '                check_warn(name, "（可选，未安装）")'),
    ('hermes_cli/doctor_platform.py', '        check_warn("Venv entry point not found", "(hermes not in venv/bin/ or .venv/bin/ — reinstall with pip install -e \'.[all]\')")\n        return f.manual_issues.append(f"Reinstall entry point: cd {PROJECT_ROOT} && source venv/bin/activate && pip install -e \'.[all]\'")\n    check_ok(f"Venv entry point exists ({venv_bin.relative_to(PROJECT_ROOT)})")',
     '        check_warn("虚拟环境入口缺失", "（venv/bin/ 或 .venv/bin/ 里没有 hermes —— 用 pip install -e \'.[all]\' 重装）")\n        return f.manual_issues.append(f"重装入口：cd {PROJECT_ROOT} && source venv/bin/activate && pip install -e \'.[all]\'")\n    check_ok(f"虚拟环境入口在位（{venv_bin.relative_to(PROJECT_ROOT)}）")'),
    ('hermes_cli/doctor_platform.py', '            return check_ok(f"{display}/{link_name} → correct target")\n        check_warn(f"{display}/{link_name} points to wrong target", f"(→ {target}, expected → {expected})")',
     '            return check_ok(f"{display}/{link_name} → 指向正确")\n        check_warn(f"{display}/{link_name} 指向的目标不对", f"（→ {target}，应该是 → {expected}）")'),
    ('hermes_cli/doctor_platform.py', '            return f.issues.append(f"Broken symlink at {display}/{link_name} — run \'coco doctor --fix\'")',
     '            return f.issues.append(f"{display}/{link_name} 是坏链接 —— 跑「coco doctor --fix」")'),
    ('hermes_cli/doctor_platform.py', '        verb = "Fixed"',
     '        verb = "已修复"'),
    ('hermes_cli/doctor_platform.py', '        return check_ok(f"{display}/{link_name} exists (non-symlink)")',
     '        return check_ok(f"{display}/{link_name} 存在（是普通文件）")'),
    ('hermes_cli/doctor_platform.py', '        check_fail(f"{display}/{link_name} not found", f"({link_name} 命令在虚拟环境外可能不可用)")',
     '        check_fail(f"找不到 {display}/{link_name}", f"({link_name} 命令在虚拟环境外可能不可用)")'),
    ('hermes_cli/doctor_platform.py', '            return f.issues.append(f"Missing {display}/{link_name} symlink — run \'coco doctor --fix\'")',
     '            return f.issues.append(f"缺 {display}/{link_name} 链接 —— 跑「coco doctor --fix」")'),
    ('hermes_cli/doctor_platform.py', '        verb = "Created"',
     '        verb = "已创建"'),
    ('hermes_cli/doctor_platform.py', '    check_ok(f"{verb} symlink: {display}/{link_name} → {venv_bin}")',
     '    check_ok(f"{verb}链接：{display}/{link_name} → {venv_bin}")'),
    ('hermes_cli/doctor_platform.py', '    if verb == "Created" and str(link_dir) not in os.environ.get("PATH", "").split(os.pathsep):\n        check_warn(f"{display} is not on your PATH", "(add it to your shell config: export PATH=\\"$HOME/.local/bin:$PATH\\")")\n        f.manual_issues.append(f"Add {display} to your PATH")',
     '    if verb == "已创建" and str(link_dir) not in os.environ.get("PATH", "").split(os.pathsep):\n        check_warn(f"{display} 不在你的 PATH 里", "（加到你的 shell 配置里：export PATH=\\"$HOME/.local/bin:$PATH\\"）")\n        f.manual_issues.append(f"把 {display} 加到 PATH 里")'),
    ('hermes_cli/doctor_tools.py', '    "image_gen": "(image generation unavailable — check the provider selection and its key or SDK with \'hermes tools\')",',
     '    "image_gen": "（图片生成不可用 —— 在「coco tools」里检查服务商选择与对应的密钥或 SDK）",'),
    ('hermes_cli/doctor_tools.py', '        check_info(f"Install for faster search: {_system_package_install_cmd(\'ripgrep\')}")',
     '        check_info(f"想搜得更快可以装：{_system_package_install_cmd(\'ripgrep\')}")'),
    ('hermes_cli/doctor_tools.py', '        check_info("Docker backend is not available inside Termux (expected on Android)")',
     '        check_info("Termux 里用不了 Docker（Android 上属正常）")'),
    ('hermes_cli/doctor_tools.py', '        check_warn("Docker/Podman not found", "(optional)")',
     '        check_warn("没装 Docker/Podman", "(optional)")'),
    ('hermes_cli/doctor_tools.py', '        check_info(f"Vercel auth {line}")',
     '        check_info(f"Vercel 登录 {line}")'),
    ('hermes_cli/doctor_tools.py', '    check_info("Vercel persistence: snapshot filesystem only; live processes do not survive sandbox recreation"',
     '    check_info("Vercel 持久化：只快照文件系统；沙箱重建后运行中的进程不会保留"'),
    ('hermes_cli/doctor_tools.py', '        check_info("Running inside a container — using local terminal backend (docker-in-docker is not configured by default)")',
     '        check_info("跑在容器里 —— 用本机终端后端（默认没配 docker-in-docker）")'),
    ('hermes_cli/doctor_tools.py', '        check_ok("agent-browser", "(resolves via npx on first use)")',
     '        check_ok("agent-browser", "（首次使用时通过 npx 解析）")'),
    ('hermes_cli/doctor_tools.py', '            check_info("  Warmed npx cache for agent-browser" if warm_agent_browser_npx_cache()\n                       else "  Could not warm npx cache (offline or npx unavailable)")',
     '            check_info("已预热 agent-browser 的 npx 缓存" if warm_agent_browser_npx_cache()\n                       else "  没能预热 npx 缓存（离线或没有 npx）")'),
    ('hermes_cli/doctor_tools.py', '        check_ok("agent-browser", "(browser automation)")',
     '        check_ok("agent-browser", "（浏览器自动化）")'),
    ('hermes_cli/doctor_tools.py', '        check_warn("agent-browser found but not runnable", f"(broken symlink at {resolved}? run: npx agent-browser --version)")',
     '        check_warn("找到了 agent-browser 但跑不起来", f"（{resolved} 是坏链接？跑一下：npx agent-browser --version）")'),
    ('hermes_cli/doctor_tools.py', '        check_warn("agent-browser not installed", "(requires npm/npx on PATH)")',
     '        check_warn("没装 agent-browser", "（需要 PATH 里有 npm/npx）")'),
    ('hermes_cli/doctor_tools.py', '    check_info("Termux browser setup:")',
     '    check_info("Termux 浏览器设置：")'),
    ('hermes_cli/doctor_tools.py', '        check_info(f"Install with: cd {PROJECT_ROOT} && npx playwright install {with_deps}chromium")',
     '        check_info(f"安装方式：cd {PROJECT_ROOT} && npx playwright install {with_deps}chromium")'),
    ('hermes_cli/doctor_tools.py', '        check_warn("browser.engine=lightpanda is shadowed", f"({reason})")\n        check_info("Fix: pick Lightpanda in `hermes tools` → Browser Automation, or set browser.engine: auto")',
     '        check_warn("browser.engine=lightpanda 被遮蔽了", f"({reason})")\n        check_info("修法：在「coco tools」→ Browser Automation 里选 Lightpanda，或把 browser.engine 设成 auto")'),
    ('hermes_cli/doctor_tools.py', '                        ("Lightpanda selected but binary not found", "(browser tools will fail until it is installed)")):',
     '                        ("选了 Lightpanda 但找不到可执行文件", "（装上之前浏览器工具用不了）")):'),
    ('hermes_cli/doctor_tools.py', '        _termux_browser_hints("Node.js not found (browser tools are optional in the tested Termux path)",',
     '        _termux_browser_hints("没装 Node.js (browser tools are optional in the tested Termux path)",'),
    ('hermes_cli/doctor_tools.py', '        check_warn("Node.js not found", "(optional, needed for browser tools)")',
     '        check_warn("没装 Node.js", "（可选，浏览器工具需要）")'),
    ('hermes_cli/doctor_tools.py', '            check_ok(f"{label} deps", "(no known vulnerabilities)")',
     '            check_ok(f"{label} 依赖", "（没有已知漏洞）")'),
    ('hermes_cli/doctor_tools.py', '            check_warn(f"{label} deps", f"({critical} critical, {high} high, {moderate} moderate — {remedy})")',
     '            check_warn(f"{label} 依赖", f"（严重 {critical}、高 {high}、中 {moderate} —— {remedy}）")'),
    ('hermes_cli/doctor_tools.py', '                check_info("  ^ build-time tooling (not runtime); if manual npm remediation "',
     '                check_info("构建期工具（不影响运行）；如果要手工修 npm "'),
    ('hermes_cli/doctor_tools.py', '                check_info(f"  ^ {detail}; report/pin the fix in package-lock.json — see #116774")\n            issues.append(f"{label} has {total} npm {_plural(total)}")',
     '                check_info(f"{detail}；把修复写进 package-lock.json（见 #116774）")\n            issues.append(f"{label} 有 {total} 个 npm 漏洞")'),
    ('hermes_cli/doctor_tools.py', '            check_ok(f"{label} deps", f"({moderate} moderate {_plural(moderate)})")',
     '            check_ok(f"{label} 依赖", f"（其中中危 {moderate} 个）")'),
    ('hermes_cli/doctor_tools.py', '        check_info("Termux compatibility fallbacks:")',
     '        check_info("Termux 兼容回退：")'),
    ('hermes_cli/doctor_tools.py', '        f.issues.append("Run \'hermes setup\' to configure missing API keys for full tool access")',
     '        f.issues.append("跑「coco setup」把缺的密钥配上，工具才能全用")'),
    ('tests/hermes_cli/test_doctor.py', '        assert "hermes tools" in image_line and "system dependency" not in image_line and "unavailable" in image_line\n        assert "system dependency not met" in next(line for line in out.splitlines() if "homeassistant" in line)\n        assert any("hermes setup" in issue for issue in f.issues)',
     '        assert "coco tools" in image_line and "系统依赖" not in image_line and "不可用" in image_line\n        assert "系统依赖没装齐" in next(line for line in out.splitlines() if "homeassistant" in line)\n        assert any("coco setup" in issue for issue in f.issues)'),
    ('tests/hermes_cli/test_doctor.py', '    assert "resolves via npx on first use" in out',
     '    assert "首次使用时通过 npx 解析" in out'),
    ('tests/hermes_cli/test_doctor.py', '    assert "Warmed npx cache for agent-browser" in out\n    assert "Could not warm npx cache" not in out',
     '    assert "已预热 agent-browser 的 npx 缓存" in out\n    assert "没能预热 npx 缓存" not in out'),
    ('tests/hermes_cli/test_doctor.py', '    assert "Could not warm npx cache (offline or npx unavailable)" in out',
     '    assert "没能预热 npx 缓存（离线或没有 npx）" in out'),
    ('tests/hermes_cli/test_doctor.py', '    assert "browser.engine=lightpanda is shadowed" in out',
     '    assert "browser.engine=lightpanda 被遮蔽了" in out'),
    ('tests/hermes_cli/test_doctor.py', '    assert "Lightpanda selected but binary not found" in out',
     '    assert "选了 Lightpanda 但找不到可执行文件" in out'),
    ('tests/hermes_cli/test_doctor_audit_remedy.py', '    assert issues == ["Browser tools (agent-browser) has 2 npm vulnerabilities"]',
     '    assert issues == ["Browser tools (agent-browser) 有 2 个 npm 漏洞"]'),
    ('tests/hermes_cli/test_doctor_audit_remedy.py', '    assert "no known vulnerabilities" in out',
     '    assert "没有已知漏洞" in out'),
    ('tests/hermes_cli/test_doctor_command_install.py', '        assert "Fixed symlink" in out',
     '        assert "已修复链接" in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', 'EXPOSED_TEXT = "exposed to the WAL-reset bug"',
     'EXPOSED_TEXT = "SQLite 升级前有 WAL 重置风险"'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "state.db: journal mode could not be read" in out',
     '        assert "state.db：读不到日志模式" in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "cannot rule out WAL exposure" in out',
     '        assert "没法排除 WAL 风险" in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "state.db is in WAL mode on a cross-VM filesystem" in out',
     '        assert "state.db 在跨虚拟机文件系统（virtiofs/9p）上是 WAL 模式" in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "state.db is in WAL mode" in out',
     '        assert "state.db 是 WAL 模式" in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "state.db: rollback journal mode" in out',
     '        assert "state.db：回滚日志模式" in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "state.db: WAL journal mode" in out',
     '        assert "state.db：WAL 日志模式" in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "state.db is in WAL mode" in out\n        assert "projects.db: rollback journal mode" in out\n        assert "kanban.db: rollback journal mode" in out\n        assert "kanban/boards/myboard/kanban.db is in WAL mode" in out',
     '        assert "state.db 是 WAL 模式" in out\n        assert "projects.db：回滚日志模式" in out\n        assert "kanban.db：回滚日志模式" in out\n        assert "kanban/boards/myboard/kanban.db 是 WAL 模式" in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "state.db: rollback journal mode" in out',
     '        assert "state.db：回滚日志模式" in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "state.db: journal mode could not be read" in out\n        assert "cannot rule out WAL exposure" in out',
     '        assert "state.db：读不到日志模式" in out\n        assert "没法排除 WAL 风险" in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "state.db: journal mode could not be read" in out',
     '        assert "state.db：读不到日志模式" in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "state.db: journal mode could not be read" in out\n        assert "cannot rule out WAL exposure" not in out',
     '        assert "state.db：读不到日志模式" in out\n        assert "没法排除 WAL 风险" not in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "state.db is in WAL mode" in out and "despite database.journal_mode=delete" in out',
     '        assert "state.db 仍是 WAL 模式" in out and "database.journal_mode=delete" in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "state.db: WAL journal mode" not in out\n        assert ("To clear the exposure:" in out) is exposed',
     '        assert "state.db：WAL 日志模式" not in out\n        assert ("消除风险的办法：" in out) is exposed'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert f"state.db is held by PID {holder.pid}" in out and "state.db" in out.split("held by PID")[1]',
     '        assert f"state.db 正被占用：PID {holder.pid}" in out and "state.db" in out.split("正被占用：PID")[1]'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "cannot prove the database is quiet" in out and "open-file scan unavailable" in out',
     '        assert "没法确认数据库此刻是安静的" in out and "open-file scan unavailable" in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert "state.db: WAL journal mode" in out',
     '        assert "state.db：WAL 日志模式" in out'),
    ('tests/hermes_cli/test_doctor_journal_modes.py', '        assert re.search(r"\\(\\d[\\d.]* [KMGT]?B\\)", out)\n        assert "To clear the exposure:" in out',
     '        assert re.search(r"（(\\d[\\d.]* [KMGT]?B)）", out)\n        assert "消除风险的办法：" in out'),
    ('hermes_cli/doctor_platform.py', '    _section("s6 Supervision")',
     '    _section("s6 监管")'),
    ('hermes_cli/doctor_platform.py', '    _section("Gateway Service")',
     '    _section("网关服务")'),
    ('hermes_cli/doctor_platform.py', '    if not check_bool(linger_enabled, ("Systemd linger enabled", "(gateway service survives logout)"),\n                      ("Systemd linger disabled", "(gateway may stop after logout)")):',
     '    if not check_bool(linger_enabled, ("systemd linger 已开启", "（退出登录后网关服务仍在跑）"),\n                      ("systemd linger 未开启", "（退出登录后网关可能会停）")):'),
    ('hermes_cli/doctor_platform.py', '                   (f"SQLite {sqlite3.sqlite_version} (WAL-reset bug)", _sqlite_upgrade_hint()))',
     '                   (f"SQLite {sqlite3.sqlite_version}（有 WAL 重置风险）", _sqlite_upgrade_hint()))'),
    ('hermes_cli/doctor_platform.py', '    _section("Command Installation")',
     '    _section("命令入口")'),
    ('hermes_cli/doctor_tools.py', '    check_bool(_safe_which("git"), "git", ("git not found", "(optional)"))\n    if not check_bool(_safe_which("rg"), ("ripgrep (rg)", "(faster file search)"),\n                      ("ripgrep (rg) not found", "(file search uses grep fallback)")):',
     '    check_bool(_safe_which("git"), "git", ("没找到 git", "(optional)"))\n    if not check_bool(_safe_which("rg"), ("ripgrep (rg)", "（搜索更快）"),\n                      ("没找到 ripgrep (rg)", "（搜索退回用 grep）")):'),
    ('hermes_cli/doctor_tools.py', '    if not check_bool(_chromium_installed(), ("Playwright Chromium", "(browser engine)"),\n                      ("Playwright Chromium not installed", "(browser_* tools will be hidden from the agent)")):',
     '    if not check_bool(_chromium_installed(), ("Playwright Chromium", "（浏览器引擎）"),\n                      ("没装 Playwright Chromium", "（浏览器类工具会对模型隐藏）")):'),
    ('hermes_cli/doctor_platform.py', '    check_bool(sys.prefix != sys.base_prefix, "Virtual environment active", ("Not in virtual environment", "(推荐)"))',
     '    check_bool(sys.prefix != sys.base_prefix, "虚拟环境正常", ("不在虚拟环境里", "（推荐用虚拟环境）"))'),
    ('hermes_cli/auth_codex.py', '_NO_CREDENTIALS_MSG = "No Codex credentials stored. Run `{relogin}` to authenticate."',
     '_NO_CREDENTIALS_MSG = "还没存 Codex 的凭据。跑 `{relogin}` 完成登录。"'),
    ('hermes_cli/auth_xai.py', '            "No xAI OAuth credentials stored. Select xAI Grok OAuth (SuperGrok / Premium+) in `hermes model`.",',
     '            "还没存 xAI 的登录凭据。在「coco model」里选 xAI Grok OAuth（SuperGrok / Premium+）。",'),
    ('hermes_cli/doctor.py', '            check_info("codex CLI not installed (optional — only required to import tokens from an existing Codex CLI login)")',
     '            check_info("没装 codex CLI（可选 —— 只有想从已有的 Codex CLI 登录导入令牌时才需要）")'),
    ('hermes_cli/doctor.py', '    logged_in = check_bool(status.get("logged_in"), (label, ok_detail), (label, "(not logged in)"))',
     '    logged_in = check_bool(status.get("logged_in"), (label, ok_detail), (label, "（未登录）"))'),
    ('hermes_cli/doctor_config.py', '        check_ok("No deprecated config keys or env vars")',
     '        check_ok("没有过时的配置项或环境变量")'),
    ('hermes_cli/doctor_config.py', '        check_warn(f"Deprecated: {legacy}", f"(use {replacement} instead)")\n        check_info(f"Replace {legacy} → {replacement} (warn-only; not auto-migrated here)")',
     '        check_warn(f"已过时：{legacy}", f"（改用 {replacement}）")\n        check_info(f"把 {legacy} 换成 {replacement}（只提示，这里不自动迁移）")'),
    ('hermes_cli/doctor_config.py', '        check_warn(f"Breaking Relay migration: {legacy}", f"({replacement})")\n        check_info(f"Migrate {legacy}: {replacement}")',
     '        check_warn(f"中转插件迁移会影响使用：{legacy}", f"（{replacement}）")\n        check_info(f"迁移 {legacy}：{replacement}")'),
    ('hermes_cli/doctor_config.py', '    check_ok(f"Managed scope active: {n_cfg} config key(s), {n_env} env key(s) pinned by {managed_dir}")',
     '    check_ok(f"托管配置生效：{managed_dir} 固定了 {n_cfg} 个配置项、{n_env} 个环境变量")'),
    ('hermes_cli/doctor_config.py', '        check_info(f"managed dir set via HERMES_MANAGED_DIR={managed_dir}")',
     '        check_info(f"托管目录来自 HERMES_MANAGED_DIR={managed_dir}")'),
    ('hermes_cli/doctor_config.py', '        check_warn(f"MCP server \'{name}\' has suspicious stdio command", "; ".join(issues_found))\n        f.manual_issues.append(f"Review/remove mcp_servers.{name} in config.yaml; rotate any credentials that may have been exposed.")',
     '        check_warn(f"MCP 服务「{name}」的 stdio 命令可疑", "; ".join(issues_found))\n        f.manual_issues.append(f"请在 config.yaml 里检查或删除 mcp_servers.{name}；可能已暴露的凭据请及时更换。")'),
    ('hermes_cli/doctor_config.py', '        check_ok("No suspicious MCP stdio commands")',
     '        check_ok("MCP 的 stdio 命令没有可疑项")'),
    ('hermes_cli/doctor_config.py', '        check_ok(f"{_DHH}/.env file exists")',
     '        check_ok(f"{_DHH}/.env 存在")'),
    ('hermes_cli/doctor_config.py', '        if not check_bool(_has_provider_env_config(content), "API key or custom endpoint configured", f"No API key found in {_DHH}/.env"):\n            f.issues.append("Run \'hermes setup\' to configure API keys")',
     '        if not check_bool(_has_provider_env_config(content), "密钥或自定义接口已配置", f"{_DHH}/.env 里没找到密钥"):\n            f.issues.append("跑「coco setup」配置密钥")'),
    ('hermes_cli/doctor_config.py', '        check_ok(".env file exists (in project directory)")',
     '        check_ok(".env 存在（在项目目录里）")'),
    ('hermes_cli/doctor_config.py', '        check_fail(f"{_DHH}/.env file missing")',
     '        check_fail(f"{_DHH}/.env 缺失")'),
    ('hermes_cli/doctor_config.py', '            check_ok(f"Created empty {_DHH}/.env")\n            check_info("Run \'hermes setup\' to configure API keys")',
     '            check_ok(f"已创建空的 {_DHH}/.env")\n            check_info("跑「coco setup」配置密钥")'),
    ('hermes_cli/doctor_config.py', '            check_info("Run \'hermes setup\' to create one")\n            f.issues.append("Run \'hermes setup\' to create .env")',
     '            check_info("跑「coco setup」创建一个")\n            f.issues.append("跑「coco setup」创建 .env")'),
    ('hermes_cli/doctor_config.py', '        check_warn(f"model.default \'{default_model}\' uses a vendor/model slug but provider is \'{provider_raw}\'",',
     '        check_warn(f"model.default「{default_model}」写成了「厂商/模型」格式，但 provider 是「{provider_raw}」",'),
    ('hermes_cli/doctor_config.py', '        issues.append(f"model.default \'{default_model}\' is vendor-prefixed but model.provider is \'{provider_raw}\'. "',
     '        issues.append(f"model.default「{default_model}」带了厂商前缀，但 model.provider 是「{provider_raw}」。"'),
    ('hermes_cli/doctor_config.py', '            check_warn(f"auxiliary.{task}.provider \'{provider}\' resolved without credentials", f"({runtime.get(\'provider\')} @ {runtime.get(\'base_url\')})")',
     '            check_warn(f"auxiliary.{task}.provider「{provider}」解析出来却没有凭据", f"（{runtime.get(\'provider\')} @ {runtime.get(\'base_url\')}）")'),
    ('hermes_cli/doctor_config.py', '        check_ok("auxiliary task routing resolves: " + ", ".join(ok))',
     '        check_ok("辅助任务的模型路由解析结果：" + ", ".join(ok))'),
    ('hermes_cli/doctor_config.py', '        check_ok(f"{_DHH}/config.yaml exists")',
     '        check_ok(f"{_DHH}/config.yaml 存在")'),
    ('hermes_cli/doctor_config.py', '        check_ok("cli-config.yaml exists (in project directory)")',
     '        check_ok("cli-config.yaml 存在（在项目目录里）")'),
    ('hermes_cli/doctor_config.py', '        check_ok(f"Created {_DHH}/config.yaml from {\'cli-config.yaml.example\' if example_config.exists() else \'defaults\'}")',
     '        check_ok(f"已创建 {_DHH}/config.yaml（来源：{\'cli-config.yaml.example\' if example_config.exists() else \'defaults\'}）")'),
    ('hermes_cli/doctor_config.py', '        check_warn("config.yaml not found", "(using defaults)")',
     '        check_warn("找不到 config.yaml", "（用默认值）")'),
    ('hermes_cli/doctor_config.py', '    if check_bool(current_ver >= latest_ver, f"Config version up to date (v{current_ver})", outdated):',
     '    if check_bool(current_ver >= latest_ver, f"配置版本已是最新（v{current_ver}）", outdated):'),
    ('hermes_cli/doctor_config.py', '        f.issues.append("Run \'hermes doctor --fix\' or \'hermes setup\' to migrate config")',
     '        f.issues.append("跑「coco doctor --fix」或「coco setup」迁移配置")'),
    ('hermes_cli/doctor_config.py', '        check_ok("Config migrated to latest version")',
     '        check_ok("配置已迁移到最新版本")'),
    ('hermes_cli/doctor_config.py', '        check_warn(f"Auto-migration failed: {mig_err}")\n        f.issues.append("Run \'hermes setup\' to migrate config")',
     '        check_warn(f"自动迁移失败：{mig_err}")\n        f.issues.append("跑「coco setup」迁移配置")'),
    ('hermes_cli/doctor_config.py', '    check_warn(f"Stale root-level config keys: {\', \'.join(stale_root_keys)}", "(should be under \'model:\' section)")',
     '    check_warn(f"根级残留的配置项：{\', \'.join(stale_root_keys)}", "（应该放在 model: 段里）")'),
    ('hermes_cli/doctor_config.py', '        f.issues.append("Stale root-level provider/base_url in config.yaml — run \'hermes doctor --fix\'")',
     '        f.issues.append("config.yaml 根级还留着 provider/base_url —— 跑「coco doctor --fix」")'),
    ('hermes_cli/doctor_config.py', '    check_ok("Migrated stale root-level keys into model section")',
     '    check_ok("已把根级残留的配置项迁到 model 段")'),
    ('hermes_cli/doctor_config.py', '    check_warn(f"HERMES_MAX_ITERATIONS={env_ghost} in .env shadows agent.max_turns={cfg_max_turns} in config.yaml",',
     '    check_warn(f".env 里的 HERMES_MAX_ITERATIONS={env_ghost} 会盖掉 config.yaml 的 agent.max_turns={cfg_max_turns}",'),
    ('hermes_cli/doctor_config.py', '        f.issues.append("Stale HERMES_MAX_ITERATIONS in .env shadows config.yaml — run \'hermes doctor --fix\'")',
     '        f.issues.append(".env 里残留的 HERMES_MAX_ITERATIONS 会盖住 config.yaml —— 跑「coco doctor --fix」")'),
    ('hermes_cli/doctor_config.py', '        check_ok(f"Removed stale HERMES_MAX_ITERATIONS from .env (config.yaml agent.max_turns={cfg_max_turns} is now authoritative)")',
     '        check_ok(f"已从 .env 删掉残留的 HERMES_MAX_ITERATIONS（现在以 config.yaml 的 agent.max_turns={cfg_max_turns} 为准）")'),
    ('hermes_cli/doctor_config.py', '        check_warn("Could not remove HERMES_MAX_ITERATIONS from .env")\n        f.manual_issues.append(f"Manually delete the HERMES_MAX_ITERATIONS line from {_DHH}/.env — config.yaml agent.max_turns is authoritative.")',
     '        check_warn("没能从 .env 删掉 HERMES_MAX_ITERATIONS")\n        f.manual_issues.append(f"请手工删掉 {_DHH}/.env 里的 HERMES_MAX_ITERATIONS 行 —— 以 config.yaml 的 agent.max_turns 为准。")'),
    ('hermes_cli/doctor_config.py', '    _section("Config Structure")',
     '    _section("配置结构")'),
    ('hermes_cli/doctor_config.py', '        check_warn(f"Legacy custom_providers entry \'{label}\' has no providers: twin",',
     '        check_warn(f"旧的 custom_providers 条目「{label}」在新写法里找不到对应项",'),
    ('hermes_cli/doctor_config.py', '        check_ok("No retired xAI models in config")',
     '        check_ok("配置里没有已下线的 xAI 模型")'),
    ('hermes_cli/doctor_config.py', '    check_info(f"Migration guide: {MIGRATION_GUIDE_URL}")\n    f.manual_issues.append(f"Update {len(retired_refs)} retired xAI model reference(s) in config.yaml — see {MIGRATION_GUIDE_URL}")',
     '    check_info(f"迁移指南：{MIGRATION_GUIDE_URL}")\n    f.manual_issues.append(f"config.yaml 里有 {len(retired_refs)} 处已下线的 xAI 模型引用，请更新 —— 见 {MIGRATION_GUIDE_URL}")'),
    ('hermes_cli/doctor_config.py', '        check_ok(f"No enabled plugin imports paths removed on {COMPAT_REMOVAL}")',
     '        check_ok(f"没有启用的插件还在用 {COMPAT_REMOVAL} 已移除的导入路径")'),
    ('hermes_cli/doctor_config.py', '    check_info("Details: hermes plugins compat")',
     '    check_info("详情：coco plugins compat")'),
    ('hermes_cli/doctor_connectivity.py', '        return _row(name, "warn", "(not configured)")',
     '        return _row(name, "warn", "（未配置）")'),
    ('hermes_cli/doctor_live.py', '        return ProbeResult(name, "skip", "(not configured)")',
     '        return ProbeResult(name, "skip", "（未配置）")'),
    ('hermes_cli/doctor_live.py', '        return ProbeResult("Browser", "skip", "(not configured)")',
     '        return ProbeResult("Browser", "skip", "（未配置）")'),
    ('hermes_cli/doctor_platform.py', '            check_ok(name, "(optional)" if optional else "")',
     '            check_ok(name, "（可选）" if optional else "")'),
    ('hermes_cli/doctor_state.py', '        (logical, lambda: f"logical size {_human_bytes(logical)}"),\n        (stats.get("page_count"), lambda: f"{stats[\'page_count\']:,} pages"),\n        (freelist, lambda: f"{freelist:,} free"),',
     '        (logical, lambda: f"占用 {_human_bytes(logical)}"),\n        (stats.get("page_count"), lambda: f"{stats[\'page_count\']:,} 页"),\n        (freelist, lambda: f"{freelist:,} 页空闲"),'),
    ('hermes_cli/doctor_state.py', '        (stats.get("messages"), lambda: f"{stats[\'messages\']:,} messages"),\n        (stats.get("sessions"), lambda: f"{stats[\'sessions\']:,} sessions"),',
     '        (stats.get("messages"), lambda: f"{stats[\'messages\']:,} 条消息"),\n        (stats.get("sessions"), lambda: f"{stats[\'sessions\']:,} 个会话"),'),
    ('hermes_cli/doctor_state.py', '        (holders, lambda: f"{holders} process(es) holding the DB open{host_note}"),',
     '        (holders, lambda: f"{holders} 个进程打开着这个库{host_note}"),'),
    ('hermes_cli/doctor_state.py', '        lines.append(("info", "FTS tables: " + (", ".join(present) if present else "none"), ""))',
     '        lines.append(("info", "全文检索表：" + (", ".join(present) if present else "无"), ""))'),
    ('hermes_cli/doctor_state.py', '    ensure_dir(f, should_fix, hermes_home, f"{_DHH} directory exists", f"Created {_DHH} directory", f"{_DHH} not found")',
     '    ensure_dir(f, should_fix, hermes_home, f"{_DHH} 目录存在", f"已创建 {_DHH} 目录", f"找不到 {_DHH}")'),
    ('hermes_cli/doctor_state.py', '        ensure_dir(f, should_fix, hermes_home / subdir_name, f"{_DHH}/{subdir_name}/ exists",\n                   f"Created {_DHH}/{subdir_name}/", f"{_DHH}/{subdir_name}/ not found")',
     '        ensure_dir(f, should_fix, hermes_home / subdir_name, f"{_DHH}/{subdir_name}/ 存在",\n                   f"已创建 {_DHH}/{subdir_name}/", f"找不到 {_DHH}/{subdir_name}/")'),
    ('hermes_cli/doctor_state.py', '            check_ok(f"{_DHH}/SOUL.md exists (persona configured)")',
     '            check_ok(f"{_DHH}/SOUL.md 存在（已配置人格）")'),
    ('hermes_cli/doctor_state.py', '            check_info(f"{_DHH}/SOUL.md exists but is empty — edit it to customize personality")',
     '            check_info(f"{_DHH}/SOUL.md 存在但是空的 —— 编辑它可以定制人格")'),
    ('hermes_cli/doctor_state.py', '        check_warn(f"{_DHH}/SOUL.md not found", "(create it to give Hermes a custom personality)")',
     '        check_warn(f"找不到 {_DHH}/SOUL.md", "（创建它可以给 Coco 定制人格）")'),
    ('hermes_cli/doctor_state.py', '            check_ok(f"Created {_DHH}/SOUL.md with basic template")',
     '            check_ok(f"已用基础模板创建 {_DHH}/SOUL.md")'),
    ('hermes_cli/doctor_state.py', '        return check_info("Built-in memory files disabled by config")',
     '        return check_info("记忆文件已被配置关掉")'),
    ('hermes_cli/doctor_state.py', '    ensure_dir(f, should_fix, memories_dir, f"{_DHH}/memories/ directory exists", f"Created {_DHH}/memories/",',
     '    ensure_dir(f, should_fix, memories_dir, f"{_DHH}/memories/ 目录存在", f"已创建 {_DHH}/memories/",'),
    ('hermes_cli/doctor_state.py', '            check_ok(f"{fname} exists ({len((memories_dir / fname).read_text(encoding=\'utf-8\').strip())} chars)")',
     '            check_ok(f"{fname} 存在（{len((memories_dir / fname).read_text(encoding=\'utf-8\').strip())} 字符）")'),
    ('hermes_cli/doctor_state.py', '            check_info(f"{fname} not created yet (will be created when the agent first writes a memory)")',
     '            check_info(f"{fname} 还没创建（第一次写记忆时会自动建）")'),
    ('hermes_cli/doctor_state.py', '    check_ok(f"{_DHH}/cache/scratch/ is the scratch dir (TMPDIR; {size}, entries pruned after {SCRATCH_MAX_IDLE_HOURS}h idle)")',
     '    check_ok(f"{_DHH}/cache/scratch/ 是临时目录（TMPDIR；{size}，闲置 {SCRATCH_MAX_IDLE_HOURS} 小时后自动清理）")'),
    ('hermes_cli/doctor_state.py', '        check_info(f"TMPDIR={tmpdir} is set by you or the OS, so Hermes leaves it alone")',
     '        check_info(f"TMPDIR={tmpdir} 是你或系统设的，Coco 不会去动它")'),
    ('hermes_cli/doctor_state.py', '        check_info("state.db write-health probe skipped: store is held by a live writer and larger than 1 GB "\n                   "(run \'hermes doctor --fix\' to probe it)")',
     '        check_info("跳过 state.db 的写入体检：库正被写入进程占用且大于 1 GB "\n                   "（跑「coco doctor --fix」可以强制检查）")'),
    ('hermes_cli/doctor_state.py', '        check_warn(not_fixed_label, f"({report.get(\'error\')}; backup: {report.get(\'backup_path\')})")',
     '        check_warn(not_fixed_label, f"（{report.get(\'error\')}；备份：{report.get(\'backup_path\')}）")'),
    ('hermes_cli/doctor_state.py', '    check_ok(ok_label, f"(strategy: {report.get(\'strategy\')}; backup: {backup_name})")',
     '    check_ok(ok_label, f"（策略：{report.get(\'strategy\')}；备份：{backup_name}）")'),
    ('hermes_cli/doctor_state.py', '    check_warn(f"{_DHH}/state.db has structural corruption (canonical tables/indexes damaged, "\n               "not the FTS index)", f"({reason})")',
     '    check_warn(f"{_DHH}/state.db 结构性损坏（核心表/索引坏了，不是 FTS 索引）", f"（{reason}）")'),
    ('hermes_cli/doctor_state.py', '        return check_warn(f"{_DHH}/state.db exists but has issues: {exc}")',
     '        return check_warn(f"{_DHH}/state.db 存在但有问题：{exc}")'),
    ('hermes_cli/doctor_state.py', '    check_warn(f"{_DHH}/state.db schema is malformed (sessions hidden until repaired)", f"({exc})")',
     '    check_warn(f"{_DHH}/state.db 表结构异常（修好之前会话会被隐藏）", f"（{exc}）")'),
    ('hermes_cli/doctor_state.py', '        check_ok(f"{_DHH}/state.db exists ({_session_count(state_db_path)} sessions)")',
     '        check_ok(f"{_DHH}/state.db 存在（{_session_count(state_db_path)} 个会话）")'),
    ('hermes_cli/doctor_state.py', '        check_warn(f"{_DHH}/state.db fails a write-health probe (FTS index may be corrupt)", f"({_write_reason})")',
     '        check_warn(f"{_DHH}/state.db 写入体检不通过（FTS 索引可能坏了）", f"（{_write_reason}）")'),
    ('hermes_cli/doctor_state.py', '    with warn_on_error("state.db stats unavailable ({e})", "", report=lambda t, _d: check_info(t)):',
     '    with warn_on_error("取不到 state.db 统计（{e}）", "", report=lambda t, _d: check_info(t)):'),
    ('hermes_cli/doctor_state.py', '                issues.append("state.db is large — enable sessions.auto_prune in config.yaml"',
     '                issues.append("state.db 偏大 —— 可以在 config.yaml 里打开 sessions.auto_prune"'),
    ('hermes_cli/doctor_state.py', '                check_warn(title, "(normal while Desktop or the gateway is running, or state.db cannot be "',
     '                check_warn(title, "（桌面端或网关在跑时属正常，或者 state.db 读不了"'),
    ('hermes_cli/doctor_state.py', '            check_warn(title, "(may indicate missed checkpoints)")',
     '            check_warn(title, "（可能是漏了检查点）")'),
    ('hermes_cli/doctor_state.py', '                    check_warn("WAL checkpoint skipped: could not take exclusive ownership of state.db",',
     '                    check_warn("跳过 WAL 检查点：拿不到 state.db 的独占所有权",'),
    ('hermes_cli/doctor_state.py', '            check_ok(f"WAL checkpoint performed ({size // 1024}K → {wal_size() // 1024}K)")',
     '            check_ok(f"已做 WAL 检查点（{size // 1024}K → {wal_size() // 1024}K）")'),
    ('hermes_cli/doctor_state.py', '            check_info(f"WAL file is {size // (1024*1024)} MB (normal for active sessions)")',
     '            check_info(f"WAL 文件 {size // (1024*1024)} MB（会话活跃时属正常）")'),
    ('hermes_cli/doctor_state.py', '    check_warn(f"{_DHH}/state.db: {len(pids)} process(es) still hold a retired WAL generation ({rendered})",\n               "(every new session refuses to open until they exit; health/stats probes skipped)")\n    f.issues.append(f"state.db retired WAL generation held by {rendered}{host_gateway_note()} — stop the host "\n                    f"gateway, dashboard and cron writers among them (\'hermes {profile_cli_selector()}gateway "\n                    "stop\' stops the ONE host process serving every profile, quit the Desktop app), do not "\n                    "delete the WAL yourself, then rerun \'hermes doctor\'")',
     '    check_warn(f"{_DHH}/state.db：还有 {len(pids)} 个进程占着已废弃的 WAL 版本（{rendered}）",\n               "（它们不退出，新会话就打不开；健康检查与统计也会跳过）")\n    f.issues.append(f"state.db 的旧 WAL 版本被 {rendered}{host_gateway_note()} 占着 —— 请把这些进程里的网关、"\n                    f"看板与定时写入都停掉（「coco {profile_cli_selector()}gateway stop」会停掉那个服务全部配置的唯一主进程；"\n                    "顺带退出桌面端），不要自己删 WAL，然后重跑「coco doctor」")'),
    ('hermes_cli/doctor_state.py', '        check_info(f"{_DHH}/state.db not created yet (will be created on first session)")',
     '        check_info(f"{_DHH}/state.db 还没创建（第一次会话时自动建）")'),
    ('hermes_cli/doctor_state.py', '    if check_bool(hub_dir.exists(), "Skills Hub directory exists", ("Skills Hub directory not initialized", "(run: hermes skills list)")):',
     '    if check_bool(hub_dir.exists(), "技能源目录存在", ("技能源目录还没初始化", "（跑：coco cli skills list）")):'),
    ('hermes_cli/doctor_state.py', '                check_ok(f"Lock file OK ({count} hub-installed skill(s))")',
     '                check_ok(f"锁文件正常（{count} 个从技能源装的技能）")'),
    ('hermes_cli/doctor_state.py', '            check_warn(f"{q_count} skill(s) in quarantine", "(pending review)")',
     '            check_warn(f"{q_count} 个技能在隔离区", "（待复核）")'),
    ('hermes_cli/doctor_state.py', '        check_ok("GitHub token configured", "(validity checked under API Connectivity)")',
     '        check_ok("GitHub 令牌已配置", "（有效性在「模型服务连通性」里检查）")'),
    ('hermes_cli/doctor_state.py', '        check_bool(_gh_authenticated(), ("GitHub authenticated via gh CLI", "(full API access — no GITHUB_TOKEN needed)"),',
     '        check_bool(_gh_authenticated(), ("已通过 gh CLI 登录 GitHub", "（完整 API 权限 —— 不需要配 GITHUB_TOKEN）"),'),
    ('hermes_cli/doctor_state.py', '                   ("Honcho config not found", "run: hermes memory setup"))',
     '                   ("Honcho config not found", "跑：coco cli memory setup"))'),
    ('hermes_cli/doctor_state.py', '        check_info(f"Honcho disabled (set enabled: true in {cfg_path} to activate)")',
     '        check_info(f"Honcho 没启用（在 {cfg_path} 里设 enabled: true 可打开）")'),
    ('hermes_cli/doctor_state.py', '        _fail_and_issue("Honcho API key or base URL not set", "run: hermes memory setup",',
     '        _fail_and_issue("Honcho API key or base URL not set", "跑：coco cli memory setup",'),
    ('hermes_cli/doctor_state.py', '            check_ok("Honcho connected", f"workspace={hcfg.workspace_id} mode={hcfg.recall_mode} freq={hcfg.write_frequency}")',
     '            check_ok("Honcho 已连接", f"工作区={hcfg.workspace_id} 模式={hcfg.recall_mode} 频率={hcfg.write_frequency}")'),
    ('hermes_cli/doctor_state.py', '        check_ok("Mem0 API key configured")\n        check_info(f"user_id={mem0_cfg.get(\'user_id\', \'?\')}  agent_id={mem0_cfg.get(\'agent_id\', \'?\')}")',
     '        check_ok("Mem0 的密钥已配置")\n        check_info(f"用户={mem0_cfg.get(\'user_id\', \'?\')}  智能体={mem0_cfg.get(\'agent_id\', \'?\')}")'),
    ('hermes_cli/doctor_state.py', '        check_ok(f"{name} provider active")',
     '        check_ok(f"{name} 记忆服务已启用")'),
    ('hermes_cli/doctor_state.py', '        check_warn(f"{name} configured but not available", "run: hermes memory status")',
     '        check_warn(f"{name} 配置了但不可用", "跑：coco cli memory status")'),
    ('hermes_cli/doctor_state.py', '        check_warn(f"{name} plugin not found", "run: hermes memory setup")',
     '        check_warn(f"找不到 {name} 插件", "跑：coco cli memory setup")'),
    ('hermes_cli/doctor_state.py', '        check_ok("Built-in memory active", "(no external provider configured — this is fine)")',
     '        check_ok("内置记忆已启用", "（没配外部记忆服务，这样就行）")'),
    ('hermes_cli/doctor_state.py', '            check_warn(f"{label} check failed", str(_e))',
     '            check_warn(f"{label} 检查失败", str(_e))'),
    ('hermes_cli/doctor_state.py', '        check_warn(f"{label} check failed", str(_e))',
     '        check_warn(f"{label} 检查失败", str(_e))'),
    ('hermes_cli/doctor_state.py', '    _section("Profiles")\n    check_ok(f"{len(named_profiles)} profile(s) found")',
     '    _section("配置档（profiles）")\n    check_ok(f"找到 {len(named_profiles)} 个配置档")'),
    ('hermes_cli/doctor_state.py', '        check_ok(f"  {p.name}: {\', \'.join(parts) if parts else \'configured\'}")',
     '        check_ok(f"  {p.name}：{\', \'.join(parts) if parts else \'已配置\'}")'),
    ('hermes_cli/doctor_state.py', '                    check_warn(f"Orphan alias: {wrapper.name} → profile \'{_m.group(1)}\' no longer exists")',
     '                    check_warn(f"多余的命令别名：{wrapper.name} → 指向的配置档「{_m.group(1)}」已不存在")'),
    ('hermes_cli/doctor_state.py', '        check_warn("Duplicate platform credential across profiles", f"({line})")',
     '        check_warn("多个配置档用了同一套平台凭据", f"（{line}）")'),
    ('hermes_cli/doctor_tools.py', '        return "(runtime-gated; loaded only for dispatcher-spawned workers)"',
     '        return "（按需加载：只在派发的工作进程里启用）"'),
    ('hermes_cli/doctor_tools.py', '                    else ("warn", capability, f"({name} selected; provider not configured)"))',
     '                    else ("warn", capability, f"（选了 {name}，但服务商没配）"))'),
    ('tests/hermes_cli/test_doctor.py', '        assert "Built-in memory active" in out',
     '        assert "内置记忆已启用" in out'),
    ('tests/hermes_cli/test_doctor.py', '        assert ("MEMORY.md exists" in out) is memory_enabled',
     '        assert ("MEMORY.md 存在" in out) is memory_enabled'),
    ('tests/hermes_cli/test_doctor.py', '        assert ("Built-in memory files disabled by config" in out) is not memory_enabled',
     '        assert ("记忆文件已被配置关掉" in out) is not memory_enabled'),
    ('tests/hermes_cli/test_doctor.py', '            f"model.default \'{default_model}\' uses a vendor/model slug but provider is \'{provider}\'"',
     '            f"model.default「{default_model}」写成了「厂商/模型」格式，但 provider 是「{provider}」"'),
    ('tests/hermes_cli/test_doctor.py', '        "model.default \'deepseek/deepseek-v4-flash\' uses a vendor/model slug but provider is "',
     '        "model.default「deepseek/deepseek-v4-flash」写成了「厂商/模型」格式，但 provider 是 "'),
    ('tests/hermes_cli/test_doctor.py', '        "model.default \'nvidia/z-ai/glm-5.2\' uses a vendor/model slug "\n        "but provider is \'openai-api\'"',
     '        "model.default「nvidia/z-ai/glm-5.2」写成了「厂商/模型」格式，"\n        "但 provider 是「openai-api」"'),
    ('tests/hermes_cli/test_doctor.py', '    assert "API key or custom endpoint configured" in out',
     '    assert "密钥或自定义接口已配置" in out'),
    ('tests/hermes_cli/test_doctor.py', '        assert "shadows" in out',
     '        assert "会盖" in out'),
    ('tests/hermes_cli/test_doctor.py', '        assert "Removed stale HERMES_MAX_ITERATIONS" in out',
     '        assert "已从 .env 删掉残留的 HERMES_MAX_ITERATIONS" in out'),
    ('tests/hermes_cli/test_doctor.py', '        assert "shadows" not in out',
     '        assert "会盖" not in out'),
    ('tests/hermes_cli/test_doctor_wal_holder_guard.py', '    assert "4242" in out and "retired WAL" in out',
     '    assert "4242" in out and "已废弃的 WAL 版本" in out'),
    ('hermes_cli/doctor_tools.py', '        detail = f"(missing {\', \'.join(env_vars)})" if env_vars else _TOOLSET_SETUP_HINTS.get(item["name"], "（系统依赖没装齐）")',
     '        detail = f"（缺 {\', \'.join(env_vars)}）" if env_vars else _TOOLSET_SETUP_HINTS.get(item["name"], "（系统依赖没装齐）")'),
]


def classify(root: Path, entry) -> tuple:
    """返回 (状态, 详情)：OK / APPLY / ANCHOR"""
    rel, old, new = entry
    path = root / rel
    if not path.exists():
        return "ANCHOR", "文件不存在"
    text = path.read_text(encoding="utf-8")
    if old in text:
        # 同一条官方文案在文件里可能出现多次（例如同一条断言写了两处），
        # 只要官方原文还在就算没改完，避免"一半中文一半英文"被当成功。
        return "APPLY", f"{text.count(old)} 处"
    if new in text:
        return "OK", ""
    return "ANCHOR", "官方原文与中文都找不到"


def main() -> int:
    ap = argparse.ArgumentParser(description="把 Coco 的中文文案重打到官方文件里")
    ap.add_argument("--apply", action="store_true", help="真的写文件（默认只检查）")
    ap.add_argument("--list", action="store_true", help="只列出条目")
    args = ap.parse_args()

    if args.list:
        for rel, old, new in ENTRIES:
            print(f"{rel}\n  官方: {old.strip()[:70]}\n  中文: {new.strip()[:70]}")
        print(f"\n共 {len(ENTRIES)} 条")
        return 0

    # 条目之间有包含关系（同一条文案被两轮改动覆盖时）：长条目先处理，
    # 否则短的先替换会把长条目的原文切碎，长条目永远匹配不上。
    ordered = sorted(ENTRIES, key=lambda e: -len(e[1]))
    applied, pending, anchors = [], [], []
    for entry in ordered:
        status, detail = classify(REPO_ROOT, entry)
        if status == "OK":
            continue
        if status == "APPLY":
            if args.apply:
                path = REPO_ROOT / entry[0]
                text = path.read_text(encoding="utf-8")
                hits = text.count(entry[1])
                path.write_text(text.replace(entry[1], entry[2]), encoding="utf-8")
                applied.append(f"{entry[0]}（{hits} 处）")
            else:
                pending.append(entry[0])
        else:
            anchors.append((entry[0], detail))

    for rel, detail in anchors:
        print(f"  [ANCHOR] {rel} —— {detail}：按 patches/README.md 23/24 人工重做后更新本表")
    if applied:
        print(f"  已重打 {len(applied)} 处中文文案：{', '.join(sorted(set(applied)))}")
    if pending:
        print(f"  待重打 {len(pending)} 处（加 --apply 执行）：{', '.join(sorted(set(pending)))}")
    if not (anchors or applied or pending):
        print("  全部已是中文，无需处理。")
    return 1 if (anchors or pending) else 0


if __name__ == "__main__":
    sys.exit(main())
